"""Add preferences field to clients

Revision ID: 1dc4ea170981
Revises: 6e0aae243388
Create Date: 2025-10-17 00:41:46.102046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1dc4ea170981'
down_revision: Union[str, Sequence[str], None] = '6e0aae243388'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('clients', sa.Column('gender', sa.String(length=20), nullable=True))
    op.add_column('clients', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('clients', sa.Column('birthdate', sa.String(length=20), nullable=True))
    op.add_column('clients', sa.Column('preferences', sa.JSON(), nullable=True))
    op.create_index(op.f('ix_clients_email'), 'clients', ['email'], unique=True)
    op.drop_column('clients', 'style')
    op.drop_column('clients', 'notes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('clients', sa.Column('style', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_clients_email'), table_name='clients')
    op.drop_column('clients', 'preferences')
    op.drop_column('clients', 'birthdate')
    op.drop_column('clients', 'city')
    op.drop_column('clients', 'gender')
    op.drop_column('clients', 'age')
    # ### end Alembic commands ###
