"""Add artist profile fields to users

Revision ID: 6e0aae243388
Revises: fc1d27de2ba2
Create Date: 2025-10-15 23:18:43.493518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e0aae243388'
down_revision: Union[str, Sequence[str], None] = 'fc1d27de2ba2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_image_url', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('city', sa.String(), nullable=True))
    op.add_column('users', sa.Column('specialties', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('users', sa.Column('profile_url', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('gallery_images', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'gallery_images')
    op.drop_column('users', 'profile_url')
    op.drop_column('users', 'specialties')
    op.drop_column('users', 'city')
    op.drop_column('users', 'profile_image_url')
    # ### end Alembic commands ###
